# naver_api 사용해서 데이터 수집하기

In [2]:
import os 
from dotenv import load_dotenv
load_dotenv()

True

In [3]:
# client_id = os.getenv("Client_Id")
# client_secret = os.getenv("Client_Secret")
# print(client_id)
# print(client_secret)

In [4]:
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request # 인터넷에서 데이터를 다운로드하거나 웹 요청을 보내기 위해
client_id = os.getenv("Client_Id")
client_secret = os.getenv("Client_Secret")
encText = urllib.parse.quote("삼성전자") # 삼성전자를 URL에서 사용할 수 있는 형식으로 변환
url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url) # HTTP 요청 객체를 만드는 코드
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request) # 서버에 요청 보내기
rescode = response.getcode() # 응답코드 확인 
if(rescode==200): # 정상응답일 경우
    response_body = response.read() # 서버에서 받은 데이터 읽기
    print(response_body.decode('utf-8')) # 문자열로 변환후 JSON 검색 결과 출력
else:
    print("Error Code:" + rescode)

{
	"lastBuildDate":"Mon, 16 Mar 2026 16:19:21 +0900",
	"total":4366530,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"주식 배당락일 <b>삼성전자<\/b> 현대차 SK하이닉스 배당일 언제냐면...",
			"link":"https:\/\/blog.naver.com\/ggokyu\/224216535943",
			"description":"주식 배당락일 <b>삼성전자<\/b> 현대차 SK하이닉스 배당일 언제냐면... 주식에 갓 입문한 주린이라면 누구나 한 번쯤 달콤한 '배당금'을 꿈꾼다. 은행 이자보다 쏠쏠하다는 소문에 <b>삼성전자<\/b>, 현대차, SK하이닉스 같은... ",
			"bloggername":"짠테크 연구소",
			"bloggerlink":"blog.naver.com\/ggokyu",
			"postdate":"20260315"
		},
		{
			"title":"<b>삼성전자<\/b> 주가 전망 - 코스피의 함정과 외국인 매매동향",
			"link":"https:\/\/blog.naver.com\/dysaghwls\/224217572797",
			"description":"<b>삼성전자<\/b> 주가 전망 - 코스피의 함정과 외국인 매매동향 요즘 코스피 시장을 보면 지수만 놓고 봤을... 바로 <b>삼성전자<\/b>입니다. 시가총액 비중이 워낙 크기 때문에 <b>삼성전자<\/b> 주가가 움직이면 지수 역시 같이... ",
			"bloggername":"경제토대왕 부의 전술",
			"bloggerlink":"blog.naver.com\/dysaghwls",
			"postdate":"20260315"
		},
		{
			"title":"&quot;비중 33%&quot; <b>삼성전자<\/b>·SK하이닉스 주가... 코스피 '이것' 주의",
			"link":"https:\/\/blog.naver.com\/troilos\/224201995084",
			"description":"결국 우리가 지금 당장 주의해야 할 '이것'은 <b>삼성전자<\/b> 주가 급등과 SK하이닉스 주가 폭등이 완벽하게... 유례없이 가파른 <b>삼성전자<\/b> 주가 상승세와 폭발적인 SK하이닉스 주가 폭등이 시장 지수를 억지로 끌어올린... ",
			"bloggername":"블로그하는 경제비둘기",
			"bloggerlink":"blog.naver.com\/troilos",
			"postdate":"20260303"
		},
		{
			"title":"<b>삼성전자<\/b> 주가 파격 전망, '이 가격' 밑으로 겁없이 사세요",
			"link":"https:\/\/blog.naver.com\/isshoko\/224213706877",
			"description":"최근 KB증권에서 무려 '32만전자'라는 충격적인 목표가를 제시하며 시장을 흔들었는데요. 널뛰기하는... 하지만 최근의 외국인 매도세는 삼성이 싫어서 한국 시장을 떠나는 게 아닙니다. <b>삼성전자<\/b> 주가가... ",
			"bloggername":"한녕, 경제로그",
			"bloggerlink":"blog.naver.com\/isshoko",
			"postdate":"20260312"
		},
		{
			"title":"&quot;<b>삼성전자<\/b> 주가 10만원 폭락설&quot; 말도 안되는 3가지 이유",
			"link":"https:\/\/blog.naver.com\/yahoyaho08\/224212268091",
			"description":"바로 &quot;<b>삼성전자<\/b> 10만전자 갑니다&quot; 물론 희망은 자유이지만 분석이라기에는 다소 현실과 동떨어져보인다는게 제 생각. 숫자 하나를 던져놓고 공포를 극대화하는 방식으로 설득하려는 글이 아닐까 싶은데요.... ",
			"bloggername":"디노의 경제 재테크이야기",
			"bloggerlink":"blog.naver.com\/yahoyaho08",
			"postdate":"20260311"
		},
		{
			"title":"<b>삼성전자<\/b> 쉬어갈 때마다 급발진하는 주식 TOP 3",
			"link":"https:\/\/blog.naver.com\/blueshw\/224213859359",
			"description":"이번 상승장의 주도주는 누가 뭐래도 <b>삼성전자<\/b>, 하이닉스다. 하지만 주도 종목이라도 항상 오르는 건 아니다. 각종 노이즈나 이슈로 쉬어갈 때가 분명 있다 이럴 때 <b>삼성전자<\/b>에 쏠린 수급은 분산된다. 그렇다고... ",
			"bloggername":"보노의 투자 생존기",
			"bloggerlink":"blog.naver.com\/blueshw",
			"postdate":"20260312"
		},
		{
			"title":"자사주 소각 뜻, <b>삼성전자<\/b> 주식 16조 소각 이유와 장점은?",
			"link":"https:\/\/blog.naver.com\/kensan21\/224213248681",
			"description":"그중에서도 무려 16조 원이라는 기록적인 규모로 진행되는 <b>삼성전자<\/b>의 자사주 소각 소식은 많은 주식... <b>삼성전자<\/b> 주식 16조 소각 이유와 시장 반응 <b>삼성전자<\/b>가 무려 16조 원어치에 달하는 엄청난 물량의 주식을... ",
			"bloggername":"경제와 IT 정보를 한번에 머니잇",
			"bloggerlink":"blog.naver.com\/kensan21",
			"postdate":"20260312"
		},
		{
			"title":"<b>삼성전자<\/b> 주가 떨어질 때마다 모아가세요?, 지금 상황에선 맞지... ",
			"link":"https:\/\/blog.naver.com\/nasiba5083\/224209500777",
			"description":"<b>삼성전자<\/b> 주가 떨어질 때마다 모아가세요? 지금 상황에선 맞지 않습니다. 광역 딜일지도 모르겠습니다만..... 이 말은 꼭 하고 싶습니다. 유튜브, 기사 등을 보다 보면 <b>삼성전자<\/b> 주가가 떨어지기 시작하니...?... ",
			"bloggername":"콘시토르의 경제 유니버스",
			"bloggerlink":"blog.naver.com\/nasiba5083",
			"postdate":"20260309"
		},
		{
			"title":"<b>삼성전자<\/b> 주주들 난리났다 ㅋ (실제 받는 돈 계산해봄..)",
			"link":"https:\/\/blog.naver.com\/voodaddy\/224212667443",
			"description":"바로 <b>삼성전자<\/b>의 100조 특별배당 가능성이다. 글로벌 투자은행인 맥쿼리에서 보고서를 통해 이런... ㅋㅋ <b>삼성전자<\/b> 100조 특별배당 이야기의 시작 맥쿼리는 <b>삼성전자<\/b>가 반도체 슈퍼사이클에 진입할 경우... ",
			"bloggername":"흙수저 탈출 일지",
			"bloggerlink":"blog.naver.com\/voodaddy",
			"postdate":"20260312"
		},
		{
			"title":"반도체 트래킹 (과거 <b>삼성전자<\/b> 업사이클 평균 650일)",
			"link":"https:\/\/blog.naver.com\/dicecasts\/224201053439",
			"description":"참조) <b>삼성전자<\/b> 기존에 P5 일정이 더 빨라지는 중... 삼성물산 미국 건설팀들 올해 중순이후 미국 마무리 하고 평택으로 복귀하는 사람들 늘어날 듯 코스닥 150 중 반도체 종목 8 리노, 13 원익IPS, 15 이오... ",
			"bloggername":"지적호기심.활자중독.새로운 시도",
			"bloggerlink":"blog.naver.com\/dicecasts",
			"postdate":"20260303"
		}
	]
}

In [6]:
encText

'%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90'

In [7]:
response = response_body.decode('utf-8')

In [8]:
import json

In [9]:
data = json.loads(response)
print(type(data))

<class 'dict'>

In [10]:
data

{'lastBuildDate': 'Mon, 16 Mar 2026 16:19:21 +0900',
 'total': 4366530,
 'start': 1,
 'display': 10,
 'items': [{'title': '주식 배당락일 <b>삼성전자</b> 현대차 SK하이닉스 배당일 언제냐면...',
   'link': 'https://blog.naver.com/ggokyu/224216535943',
   'description': "주식 배당락일 <b>삼성전자</b> 현대차 SK하이닉스 배당일 언제냐면... 주식에 갓 입문한 주린이라면 누구나 한 번쯤 달콤한 '배당금'을 꿈꾼다. 은행 이자보다 쏠쏠하다는 소문에 <b>삼성전자</b>, 현대차, SK하이닉스 같은... ",
   'bloggername': '짠테크 연구소',
   'bloggerlink': 'blog.naver.com/ggokyu',
   'postdate': '20260315'},
  {'title': '<b>삼성전자</b> 주가 전망 - 코스피의 함정과 외국인 매매동향',
   'link': 'https://blog.naver.com/dysaghwls/224217572797',
   'description': '<b>삼성전자</b> 주가 전망 - 코스피의 함정과 외국인 매매동향 요즘 코스피 시장을 보면 지수만 놓고 봤을... 바로 <b>삼성전자</b>입니다. 시가총액 비중이 워낙 크기 때문에 <b>삼성전자</b> 주가가 움직이면 지수 역시 같이... ',
   'bloggername': '경제토대왕 부의 전술',
   'bloggerlink': 'blog.naver.com/dysaghwls',
   'postdate': '20260315'},
  {'title': "&quot;비중 33%&quot; <b>삼성전자</b>·SK하이닉스 주가... 코스피 '이것' 주의",
   'link': 'https://blog.naver.com/troilos/224201995084',
   'description': "결국 우리가 지금 당장 주의해야 할 '이것'은 <b>삼성전자</b> 주가 급등과 SK하이닉스 주가 폭등이 완벽하게... 유례없이 가파른 <b>삼성전자</b> 주가 상승세와 폭발적인 SK하이닉스 주가 폭등이 시장 지수를 억지로 끌어올린... ",
   'bloggername': '블로그하는 경제비둘기',
   'bloggerlink': 'blog.naver.com/troilos',
   'postdate': '20260303'},
  {'title': "<b>삼성전자</b> 주가 파격 전망, '이 가격' 밑으로 겁없이 사세요",
   'link': 'https://blog.naver.com/isshoko/224213706877',
   'description': "최근 KB증권에서 무려 '32만전자'라는 충격적인 목표가를 제시하며 시장을 흔들었는데요. 널뛰기하는... 하지만 최근의 외국인 매도세는 삼성이 싫어서 한국 시장을 떠나는 게 아닙니다. <b>삼성전자</b> 주가가... ",
   'bloggername': '한녕, 경제로그',
   'bloggerlink': 'blog.naver.com/isshoko',
   'postdate': '20260312'},
  {'title': '&quot;<b>삼성전자</b> 주가 10만원 폭락설&quot; 말도 안되는 3가지 이유',
   'link': 'https://blog.naver.com/yahoyaho08/224212268091',
   'description': '바로 &quot;<b>삼성전자</b> 10만전자 갑니다&quot; 물론 희망은 자유이지만 분석이라기에는 다소 현실과 동떨어져보인다는게 제 생각. 숫자 하나를 던져놓고 공포를 극대화하는 방식으로 설득하려는 글이 아닐까 싶은데요.... ',
   'bloggername': '디노의 경제 재테크이야기',
   'bloggerlink': 'blog.naver.com/yahoyaho08',
   'postdate': '20260311'},
  {'title': '<b>삼성전자</b> 쉬어갈 때마다 급발진하는 주식 TOP 3',
   'link': 'https://blog.naver.com/blueshw/224213859359',
   'description': '이번 상승장의 주도주는 누가 뭐래도 <b>삼성전자</b>, 하이닉스다. 하지만 주도 종목이라도 항상 오르는 건 아니다. 각종 노이즈나 이슈로 쉬어갈 때가 분명 있다 이럴 때 <b>삼성전자</b>에 쏠린 수급은 분산된다. 그렇다고... ',
   'bloggername': '보노의 투자 생존기',
   'bloggerlink': 'blog.naver.com/blueshw',
   'postdate': '20260312'},
  {'title': '자사주 소각 뜻, <b>삼성전자</b> 주식 16조 소각 이유와 장점은?',
   'link': 'https://blog.naver.com/kensan21/224213248681',
   'description': '그중에서도 무려 16조 원이라는 기록적인 규모로 진행되는 <b>삼성전자</b>의 자사주 소각 소식은 많은 주식... <b>삼성전자</b> 주식 16조 소각 이유와 시장 반응 <b>삼성전자</b>가 무려 16조 원어치에 달하는 엄청난 물량의 주식을... ',
   'bloggername': '경제와 IT 정보를 한번에 머니잇',
   'bloggerlink': 'blog.naver.com/kensan21',
   'postdate': '20260312'},
  {'title': '<b>삼성전자</b> 주가 떨어질 때마다 모아가세요?, 지금 상황에선 맞지... ',
   'link': 'https://blog.naver.com/nasiba5083/224209500777',
   'description': '<b>삼성전자</b> 주가 떨어질 때마다 모아가세요? 지금 상황에선 맞지 않습니다. 광역 딜일지도 모르겠습니다만..... 이 말은 꼭 하고 싶습니다. 유튜브, 기사 등을 보다 보면 <b>삼성전자</b> 주가가 떨어지기 시작하니...?... ',
   'bloggername': '콘시토르의 경제 유니버스',
   'bloggerlink': 'blog.naver.com/nasiba5083',
   'postdate': '20260309'},
  {'title': '<b>삼성전자</b> 주주들 난리났다 ㅋ (실제 받는 돈 계산해봄..)',
   'link': 'https://blog.naver.com/voodaddy/224212667443',
   'description': '바로 <b>삼성전자</b>의 100조 특별배당 가능성이다. 글로벌 투자은행인 맥쿼리에서 보고서를 통해 이런... ㅋㅋ <b>삼성전자</b> 100조 특별배당 이야기의 시작 맥쿼리는 <b>삼성전자</b>가 반도체 슈퍼사이클에 진입할 경우... ',
   'bloggername': '흙수저 탈출 일지',
   'bloggerlink': 'blog.naver.com/voodaddy',
   'postdate': '20260312'},
  {'title': '반도체 트래킹 (과거 <b>삼성전자</b> 업사이클 평균 650일)',
   'link': 'https://blog.naver.com/dicecasts/224201053439',
   'description': '참조) <b>삼성전자</b> 기존에 P5 일정이 더 빨라지는 중... 삼성물산 미국 건설팀들 올해 중순이후 미국 마무리 하고 평택으로 복귀하는 사람들 늘어날 듯 코스닥 150 중 반도체 종목 8 리노, 13 원익IPS, 15 이오... ',
   'bloggername': '지적호기심.활자중독.새로운 시도',
   'bloggerlink': 'blog.naver.com/dicecasts',
   'postdate': '20260303'}]}

In [11]:
data['items']

[{'title': '주식 배당락일 <b>삼성전자</b> 현대차 SK하이닉스 배당일 언제냐면...',
  'link': 'https://blog.naver.com/ggokyu/224216535943',
  'description': "주식 배당락일 <b>삼성전자</b> 현대차 SK하이닉스 배당일 언제냐면... 주식에 갓 입문한 주린이라면 누구나 한 번쯤 달콤한 '배당금'을 꿈꾼다. 은행 이자보다 쏠쏠하다는 소문에 <b>삼성전자</b>, 현대차, SK하이닉스 같은... ",
  'bloggername': '짠테크 연구소',
  'bloggerlink': 'blog.naver.com/ggokyu',
  'postdate': '20260315'},
 {'title': '<b>삼성전자</b> 주가 전망 - 코스피의 함정과 외국인 매매동향',
  'link': 'https://blog.naver.com/dysaghwls/224217572797',
  'description': '<b>삼성전자</b> 주가 전망 - 코스피의 함정과 외국인 매매동향 요즘 코스피 시장을 보면 지수만 놓고 봤을... 바로 <b>삼성전자</b>입니다. 시가총액 비중이 워낙 크기 때문에 <b>삼성전자</b> 주가가 움직이면 지수 역시 같이... ',
  'bloggername': '경제토대왕 부의 전술',
  'bloggerlink': 'blog.naver.com/dysaghwls',
  'postdate': '20260315'},
 {'title': "&quot;비중 33%&quot; <b>삼성전자</b>·SK하이닉스 주가... 코스피 '이것' 주의",
  'link': 'https://blog.naver.com/troilos/224201995084',
  'description': "결국 우리가 지금 당장 주의해야 할 '이것'은 <b>삼성전자</b> 주가 급등과 SK하이닉스 주가 폭등이 완벽하게... 유례없이 가파른 <b>삼성전자</b> 주가 상승세와 폭발적인 SK하이닉스 주가 폭등이 시장 지수를 억지로 끌어올린... ",
  'bloggername': '블로그하는 경제비둘기',
  'bloggerlink': 'blog.naver.com/troilos',
  'postdate': '20260303'},
 {'title': "<b>삼성전자</b> 주가 파격 전망, '이 가격' 밑으로 겁없이 사세요",
  'link': 'https://blog.naver.com/isshoko/224213706877',
  'description': "최근 KB증권에서 무려 '32만전자'라는 충격적인 목표가를 제시하며 시장을 흔들었는데요. 널뛰기하는... 하지만 최근의 외국인 매도세는 삼성이 싫어서 한국 시장을 떠나는 게 아닙니다. <b>삼성전자</b> 주가가... ",
  'bloggername': '한녕, 경제로그',
  'bloggerlink': 'blog.naver.com/isshoko',
  'postdate': '20260312'},
 {'title': '&quot;<b>삼성전자</b> 주가 10만원 폭락설&quot; 말도 안되는 3가지 이유',
  'link': 'https://blog.naver.com/yahoyaho08/224212268091',
  'description': '바로 &quot;<b>삼성전자</b> 10만전자 갑니다&quot; 물론 희망은 자유이지만 분석이라기에는 다소 현실과 동떨어져보인다는게 제 생각. 숫자 하나를 던져놓고 공포를 극대화하는 방식으로 설득하려는 글이 아닐까 싶은데요.... ',
  'bloggername': '디노의 경제 재테크이야기',
  'bloggerlink': 'blog.naver.com/yahoyaho08',
  'postdate': '20260311'},
 {'title': '<b>삼성전자</b> 쉬어갈 때마다 급발진하는 주식 TOP 3',
  'link': 'https://blog.naver.com/blueshw/224213859359',
  'description': '이번 상승장의 주도주는 누가 뭐래도 <b>삼성전자</b>, 하이닉스다. 하지만 주도 종목이라도 항상 오르는 건 아니다. 각종 노이즈나 이슈로 쉬어갈 때가 분명 있다 이럴 때 <b>삼성전자</b>에 쏠린 수급은 분산된다. 그렇다고... ',
  'bloggername': '보노의 투자 생존기',
  'bloggerlink': 'blog.naver.com/blueshw',
  'postdate': '20260312'},
 {'title': '자사주 소각 뜻, <b>삼성전자</b> 주식 16조 소각 이유와 장점은?',
  'link': 'https://blog.naver.com/kensan21/224213248681',
  'description': '그중에서도 무려 16조 원이라는 기록적인 규모로 진행되는 <b>삼성전자</b>의 자사주 소각 소식은 많은 주식... <b>삼성전자</b> 주식 16조 소각 이유와 시장 반응 <b>삼성전자</b>가 무려 16조 원어치에 달하는 엄청난 물량의 주식을... ',
  'bloggername': '경제와 IT 정보를 한번에 머니잇',
  'bloggerlink': 'blog.naver.com/kensan21',
  'postdate': '20260312'},
 {'title': '<b>삼성전자</b> 주가 떨어질 때마다 모아가세요?, 지금 상황에선 맞지... ',
  'link': 'https://blog.naver.com/nasiba5083/224209500777',
  'description': '<b>삼성전자</b> 주가 떨어질 때마다 모아가세요? 지금 상황에선 맞지 않습니다. 광역 딜일지도 모르겠습니다만..... 이 말은 꼭 하고 싶습니다. 유튜브, 기사 등을 보다 보면 <b>삼성전자</b> 주가가 떨어지기 시작하니...?... ',
  'bloggername': '콘시토르의 경제 유니버스',
  'bloggerlink': 'blog.naver.com/nasiba5083',
  'postdate': '20260309'},
 {'title': '<b>삼성전자</b> 주주들 난리났다 ㅋ (실제 받는 돈 계산해봄..)',
  'link': 'https://blog.naver.com/voodaddy/224212667443',
  'description': '바로 <b>삼성전자</b>의 100조 특별배당 가능성이다. 글로벌 투자은행인 맥쿼리에서 보고서를 통해 이런... ㅋㅋ <b>삼성전자</b> 100조 특별배당 이야기의 시작 맥쿼리는 <b>삼성전자</b>가 반도체 슈퍼사이클에 진입할 경우... ',
  'bloggername': '흙수저 탈출 일지',
  'bloggerlink': 'blog.naver.com/voodaddy',
  'postdate': '20260312'},
 {'title': '반도체 트래킹 (과거 <b>삼성전자</b> 업사이클 평균 650일)',
  'link': 'https://blog.naver.com/dicecasts/224201053439',
  'description': '참조) <b>삼성전자</b> 기존에 P5 일정이 더 빨라지는 중... 삼성물산 미국 건설팀들 올해 중순이후 미국 마무리 하고 평택으로 복귀하는 사람들 늘어날 듯 코스닥 150 중 반도체 종목 8 리노, 13 원익IPS, 15 이오... ',
  'bloggername': '지적호기심.활자중독.새로운 시도',
  'bloggerlink': 'blog.naver.com/dicecasts',
  'postdate': '20260303'}]

In [13]:
import pandas as pd

In [16]:
result={}

for item in data['items']:
    #print(item)
    for key, value in item.items():
        result.setdefault(key, []).append(value)
        # key 존재하면 기존값 반환, key가 없으면 기본값을 넣고 반환
df = pd.DataFrame(result)
df

,title,link,description,bloggername,bloggerlink,postdate
0,외국인들 <b>삼성전자</b> 팔고 셀트리온 산다는데,https://blog.naver.com/yahoyaho08/224145850607,외국인들은 어떤 종목을 매수하고 있고 우리도 <b>삼성전자</b> 팔고 외국인들이 ...,디노의 경제 재테크이야기,blog.naver.com/yahoyaho08,20260114
1,"물린 사람이 없는 <b>삼성전자</b>주가, 2026년 전망은?",https://blog.naver.com/goodbye202407/224138808514,2025년을 지나오며 <b>삼성전자</b> 주가를 두고 이런 말이 나옵니다. “이 ...,여행가는 망고주스,blog.naver.com/goodbye202407,20260109
2,"홍라희 여사 <b>삼성전자</b> 주식 대량 매도, 주가에 악재일까 기회일까?",https://blog.naver.com/totoro3123/224151135821,"반면, 소식을 접하고 의견들을 찾아보니 이번 매각을 <b>삼성전자</b>가 더 높이...",너부리의 주식경제노트,blog.naver.com/totoro3123,20260118
3,<b>삼성전자</b> 주식 2조원 규모 매도하는 이유는(상속세 및 대출금),https://blog.naver.com/lmj400/224151180213,여러분은 이번 삼성가의 결정을 보며 어떤 생각이 드셨나요? 상속세 제도에 대한 견해...,웰커넥티드,blog.naver.com/lmj400,20260118
4,"<b>삼성전자</b>, 하이닉스 언제 팔까? 나의 매도 기준 3가지",https://blog.naver.com/isshoko/224141912142,"코스피 4,600선 돌파라는 역사적 순간의 중심에는 단연 <b>삼성전자</b>와 S...","한녕, 경제로그",blog.naver.com/isshoko,20260110
5,"오늘 <b>삼성전자</b> 주가 전망, 최고가부터 실적 배당금까지",https://blog.naver.com/horizon37/224147907932,<b>삼성전자</b> 주가가 하늘 모르고 치솟고 있습니다. 커뮤니티에선 &quot;...,직장인 쩡이의 고군분투 재테크,blog.naver.com/horizon37,20260115
6,"효성중공업 주가 전망, <b>삼성전자</b> 이후 300만원 주식 등장?",https://blog.naver.com/blueshw/224143423781,<b>삼성전자</b> 이후 300만원 주식 등장? 현재 상장사 중 1주당 가장 비싼...,보노의 투자 생존기,blog.naver.com/blueshw,20260112
7,"<b>삼성전자</b> 주가 전망, 보조지표는 어떤 신호를 보내고 있을까?",https://blog.naver.com/kis6574/224151578822,차트보는 말희아빠 불과 1년 전까지만 해도 5만 원이였던 <b>삼성전자</b> 주가...,차트보는 말희아빠,blog.naver.com/kis6574,20260119
8,2025년 <b>삼성전자</b> 배당일 기준일 4분기 배당락일 주가 기준...,https://blog.naver.com/kensan21/224124740213,2025년 <b>삼성전자</b> 배당일 기준일 4분기 배당락일 주가 기준 알아보기 ...,경제와 IT 정보를 한번에 머니잇,blog.naver.com/kensan21,20251227
9,고공행진하는 <b>삼성전자</b> 주가와 원달러 환율 비교해 보니,https://blog.naver.com/rmsgud2007/224148846329,먼저 많은 투자자들이 10만 전자를 꿈꿨던 팬데믹 시기에 <b>삼성전자</b> 주가...,방구석 청년의 경제이야기,blog.naver.com/rmsgud2007,20260119

# naver api의 파라미터 설정 후 최대로 수집하기

파라미터 타입 필수 여부 설명

query: String Y 검색어. UTF-8로 인코딩되어야 합니다.

display: Integer N 한 번에 표시할 검색 결과 개수 (기본값: 10, 최댓값: 100)

start: Integer N 검색 시작 위치 (기본값: 1, 최댓값: 1000)

sort String N 검색 결과 정렬 방법
- sim: 정확도순으로 내림차순 정렬 (기본값)
- date: 날짜순으로 내림차순 정렬

In [29]:
# 라이브러리 불러오기
import os
import sys
import urllib.request
from dotenv import load_dotenv
load_dotenv()
import pandas as pd
import json
from myfunc import text_clean

# display=100으로 해서 1page에 100개 자료 수집

In [22]:
# 네이버 검색 API 예제 - 블로그 검색
client_id = os.getenv("Client_Id")
client_secret = os.getenv("Client_Secret")
encText = urllib.parse.quote("삼성전자")
parameters = "&display=100&start=1&sort=sim"
url = "https://openapi.naver.com/v1/search/blog?query=" + encText +parameters # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    response = response_body.decode('utf-8')
    data = json.loads(response)
else:
    print("Error Code:" + rescode)
    
result={}
for item in data['items']:
    #print(item)
    for key, value in item.items():
        result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

,title,link,description,bloggername,bloggerlink,postdate
0,외국인들 <b>삼성전자</b> 팔고 셀트리온 산다는데,https://blog.naver.com/yahoyaho08/224145850607,외국인들은 어떤 종목을 매수하고 있고 우리도 <b>삼성전자</b> 팔고 외국인들이 ...,디노의 경제 재테크이야기,blog.naver.com/yahoyaho08,20260114
1,"물린 사람이 없는 <b>삼성전자</b>주가, 2026년 전망은?",https://blog.naver.com/goodbye202407/224138808514,2025년을 지나오며 <b>삼성전자</b> 주가를 두고 이런 말이 나옵니다. “이 ...,여행가는 망고주스,blog.naver.com/goodbye202407,20260109
2,"홍라희 여사 <b>삼성전자</b> 주식 대량 매도, 주가에 악재일까 기회일까?",https://blog.naver.com/totoro3123/224151135821,"반면, 소식을 접하고 의견들을 찾아보니 이번 매각을 <b>삼성전자</b>가 더 높이...",너부리의 주식경제노트,blog.naver.com/totoro3123,20260118
3,<b>삼성전자</b> 주식 2조원 규모 매도하는 이유는(상속세 및 대출금),https://blog.naver.com/lmj400/224151180213,여러분은 이번 삼성가의 결정을 보며 어떤 생각이 드셨나요? 상속세 제도에 대한 견해...,웰커넥티드,blog.naver.com/lmj400,20260118
4,"<b>삼성전자</b>, 하이닉스 언제 팔까? 나의 매도 기준 3가지",https://blog.naver.com/isshoko/224141912142,"코스피 4,600선 돌파라는 역사적 순간의 중심에는 단연 <b>삼성전자</b>와 S...","한녕, 경제로그",blog.naver.com/isshoko,20260110
...,...,...,...,...,...,...
95,<b>삼성전자</b> : 레거시 디램의 왕이 돌아왔다!,https://blog.naver.com/pokara61/224134665685,HBM 시장에서 삼성은 선전할 것인가? <b>삼성전자</b>는 HBM 시장에서 올해...,포카라의 실전투자,blog.naver.com/pokara61,20260105
96,"HBM 공급망 지도 좋음 (<b>삼성전자</b>, SK하이닉스)",https://blog.naver.com/going_tothe_moon/224138...,"기업 -SK하이닉스, <b>삼성전자</b>, 마이크론 2) ASIC 설계자 (ASI...",고잉투더문,blog.naver.com/going_tothe_moon,20260108
97,<b>삼성전자</b> : 4분기 영업이익 20조원 기록,https://blog.naver.com/pokara61/224139368098,<b>삼성전자</b> 4분기 실적이 발표되었다. 분기영업이익 20조 달성으로 컨센서...,포카라의 실전투자,blog.naver.com/pokara61,20260108
98,<b>삼성전자</b> : 밸류가 낮아서 업사이드도 높다. HBM4 좋은 평가...,https://blog.naver.com/pokara61/224119442972,<b>삼성전자</b>가 내년에는 HBM4 시장에서 돌파구를 마련할 것인가? <b>삼...,포카라의 실전투자,blog.naver.com/pokara61,20251223
99,<b>삼성전자</b> 주가 오르자 '<b>삼성전자</b>우'도 10만원 돌파,https://blog.naver.com/tearhunter/224134910389,<b>삼성전자</b> 강세 속 삼선전자우도 꾸준히 상승 <b>삼성전자</b>우(우선...,웹진 [Coin Choice],blog.naver.com/tearhunter,20260105

In [17]:
"https://openapi.naver.com/v1/search/blog?query=" + encText + "&display=100&start=1&sort=sim"

'https://openapi.naver.com/v1/search/blog?query=%EC%82%BC%EC%84%B1%EC%A0%84%EC%9E%90&display=100&start=1&sort=sim'

# start = 1-1000까지 증가, 1page에 100개, 최대 1099개 정도
* 1-100
* 101-200
* 201-300
* 301-400
* 401-500
* 501-600
* 601-700
* 701-800
* 701-800
* 801-900
* 901-1000
* 1000-1100
range(시작, 끝+1, step)

In [27]:
for num in range(1,1101,100):
    #print(num)
    if num>1000:
        num -= 1
    print(num)

1
101
201
301
401
501
601
701
801
901
1000

In [30]:
result={}
for num in range(1,1101,100):
    #print(num)
    if num>1000:
        num -= 1
        
    # 네이버 검색 API 예제 - 블로그 검색
    client_id = os.getenv("Client_Id")
    client_secret = os.getenv("Client_Secret")
    encText = urllib.parse.quote("삼성전자")
    parameters = f"&display=100&start={num}&sort=sim"
    url = "https://openapi.naver.com/v1/search/blog?query=" + encText + parameters # JSON 결과
    # url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        response = response_body.decode('utf-8')
        data = json.loads(response)
    else:
        print("Error Code:" + rescode)
    
    for item in data['items']:
        #print(item)
        for key, value in item.items():
            if key in ["title", "description"]:
                value = text_clean(value)
            result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

,title,link,description,bloggername,bloggerlink,postdate
0,외국인들 삼성전자 팔고 셀트리온 산다는데,https://blog.naver.com/yahoyaho08/224145850607,외국인들은 어떤 종목을 매수하고 있고 우리도 삼성전자 팔고 외국인들이 사는 종목을 ...,디노의 경제 재테크이야기,blog.naver.com/yahoyaho08,20260114
1,물린 사람이 없는 삼성전자주가 0 년 전망은,https://blog.naver.com/goodbye202407/224138808514,0 년을 지나오며 삼성전자 주가를 두고 이런 말이 나옵니다 이 주식 물린 사람이 거...,여행가는 망고주스,blog.naver.com/goodbye202407,20260109
2,홍라희 여사 삼성전자 주식 대량 매도 주가에 악재일까 기회일까,https://blog.naver.com/totoro3123/224151135821,반면 소식을 접하고 의견들을 찾아보니 이번 매각을 삼성전자가 더 높이 날아오르기 위...,너부리의 주식경제노트,blog.naver.com/totoro3123,20260118
3,삼성전자 주식 조원 규모 매도하는 이유는 상속세 및 대출금,https://blog.naver.com/lmj400/224151180213,여러분은 이번 삼성가의 결정을 보며 어떤 생각이 드셨나요 상속세 제도에 대한 견해나...,웰커넥티드,blog.naver.com/lmj400,20260118
4,삼성전자 하이닉스 언제 팔까 나의 매도 기준 가지,https://blog.naver.com/isshoko/224141912142,코스피 00선 돌파라는 역사적 순간의 중심에는 단연 삼성전자와 SK하이닉스가 있습니...,"한녕, 경제로그",blog.naver.com/isshoko,20260110
...,...,...,...,...,...,...
1095,삼성전자 보다 뜨거운 반도체 관련주 TOP 소개,https://blog.naver.com/dkals357/224135146812,대장주인 삼성전자부터 중소형 반도체 장비 부품주까지 전반적인 온기가 확산되고 있기 ...,불개미 현이,blog.naver.com/dkals357,20260105
1096,삼성전자 주가 오르는 이유와 전망 AI 반도체 시대 핵심 기업,https://blog.naver.com/julian1986/224064835229,AI 반도체 수요가 급증하며 삼성전자 주가가 반등하고 있습니다 HBM E 양산 외국...,주택청약과 부동산 공부,blog.naver.com/julian1986,20251105
1097,0대 이상은 삼성전자 0 0은 하이닉스를 사는 이유,https://blog.naver.com/33bsh/224145038701,삼성전자는 이들에게 기회 라기보다 기본값 이다 반면 SK하이닉스를 바라보는 시선은 ...,맥코이의 부동산 투자,blog.naver.com/33bsh,20260113
1098,삼성전자는,https://blog.naver.com/sgtkim79/224148587095,HBM도이제 곧 삼성전자가 메이저 공급업체가 될겁니다 이외에도 삼성전자는 단일기업이...,-정석의 주식투자 일기-,blog.naver.com/sgtkim79,20260116
1099,포모 와서 이제와서 삼성전자로 갈아 타신다고요,https://blog.naver.com/cleo1112/224139800566,삼성 전자 실적 발표이후 살짝 내려간 주가 하지만 여전히 최고가 수준을 유지하고 있...,cleo1112의 주린이 탈출기와 엔터 이야기,blog.naver.com/cleo1112,20260109