# 03_공공데이터 API에서 데이터 수집하기_소상공인 상가 상권정보

# 1. 소상공인 상가(상권)정보 API 링크
[https://www.data.go.kr/data/15012005/openapi.do](https://www.data.go.kr/data/15012005/openapi.do)

In [2]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

* 상권정보 샘플 코드

In [3]:
# os.getenv("service_key")

In [4]:
url="https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
payload = dict(divId="indsLclsCd",key="I2", numOfRows=2, pageNo=1, type="json", serviceKey=os.getenv("service_key"))
r = requests.get(url,params=payload)
print(r.url)
print(r.status_code)
response = r.json()
response

https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsLclsCd&key=I2&numOfRows=2&pageNo=1&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
200

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202512',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA010120220700009052',
    'bizesNm': '송산유원지집단급식소',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I207',
    'indsMclsNm': '구내식당·뷔페',
    'indsSclsCd': 'I20701',
    'indsSclsNm': '구내식당',
    'ksicCd': 'I56130',
    'ksicNm': '기관 구내식당업',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29200',
    'signguNm': '광산구',
    'adongCd': '29200565',
    'adongNm': '어룡동',
    'ldongCd': '2920011100',
    'ldongNm': '박호동',
    'lnoCd': '2920011100105780013',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 578,
    'lnoSlno': 13,
    'lnoAdr': '광주광역시 광산구 박호동 578-13',
    'rdnmCd': '292003163010',
    'rdnm': '광주광역시 광산구 박호등임로',
    'bldMnno': 95,
    'bldSlno': '',
    'bldMngNo': '2920011100105780012000001',
    'bldNm': '',
    'rdnmAdr': '광주광역시 광산구 박호등임로 95',
    'oldZipcd': '506080',
    'newZipcd': '62398',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.740117533416,
    'lat': 35.1632761370996},
   {'bizesId': 'MA010120220700017876',
    'bizesNm': '세하동시내버스구내식당',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I207',
    'indsMclsNm': '구내식당·뷔페',
    'indsSclsCd': 'I20701',
    'indsSclsNm': '구내식당',
    'ksicCd': 'I56130',
    'ksicNm': '기관 구내식당업',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29140',
    'signguNm': '서구',
    'adongCd': '29140800',
    'adongNm': '서창동',
    'ldongCd': '2914012600',
    'ldongNm': '세하동',
    'lnoCd': '2914012600103850001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 385,
    'lnoSlno': 1,
    'lnoAdr': '광주광역시 서구 세하동 385-1',
    'rdnmCd': '291403009013',
    'rdnm': '광주광역시 서구 눌재로',
    'bldMnno': 470,
    'bldSlno': '',
    'bldMngNo': '2914012600103850001000001',
    'bldNm': '',
    'rdnmAdr': '광주광역시 서구 눌재로 470',
    'oldZipcd': '502151',
    'newZipcd': '62076',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.83325255775,
    'lat': 35.1190300627841}],
  'numOfRows': 2,
  'pageNo': 1,
  'totalCount': 807264}}

* 세부업종 치킨집 I21006 데이터 수집하기

In [5]:
I21006

NameError: name 'I21006' is not defined

In [ ]:
indsSclsCd

In [6]:
url = "https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
payload = dict(divId="indsSclsCd", key="I21006", numOfRows=1000, pageNo=1, type="json", serviceKey=os.getenv("service_key"))
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
response = r.json() # api 서버가 보낸 json 데이터를 python이 사용할 수 있는 자료구조로 변환
result ={}
for item in response['body']['items']:
    for key, value in item.items():
        result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=1&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
200

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800756019,고려통닭논산,연무점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4423025324108940349056057,,충청남도 논산시 연무읍 안심로 126,320833,33008,,,,127.099797,36.132234
1,MA010120220800687746,자담치킨,후평점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4211012000106830000031731,,강원특별자치도 춘천시 춘천로 270,200969,24291,,1,,127.743440,37.879891
2,MA010120220800597071,비니거니치킨호프,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1138010900100300010000226,,서울특별시 은평구 가좌로 318,122882,03451,,1,,126.910024,37.596083
3,MA010120220800454083,노랑통닭군포당동점,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4141010100109160007010332,,경기도 군포시 군포로456번길 17,435818,15856,,1,,126.945399,37.346741
4,MA010120220800485303,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1150010300111150019016021,,서울특별시 강서구 화곡로58길 29,157928,07654,,,,126.852597,37.552904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,MA010120220800390722,교촌치킨거여가락1호,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1171010700101800009005747,부국빌딩,서울특별시 송파구 문정로 143,138812,05782,,1,,127.135603,37.492488
996,MA010120220800749152,맛닭꼬,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1153010200105710016026788,양재빌딩,서울특별시 구로구 새말로8길 3,152862,08292,,,,126.884622,37.502564
997,MA010120220800694523,페리카나치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1121510300102030024008093,,서울특별시 광진구 구의로16길 23,143821,05033,,,,127.091860,37.543680
998,MA010120220800088569,누구나홀딱반한닭춘천,온의점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4211012100100730020018657,,강원특별자치도 춘천시 스포츠타운길 523,200937,24429,,1,,127.714094,37.868342
999,MA010120220800090053,노랑통닭송탄점,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4122010100108160002005525,우측상가,경기도 평택시 특구로23번길 19,459813,17774,,1,,127.062103,37.067556

# 첫 페이지 수집 내용에서 total_count 추출 후 페이지 수 계산하고 전체 데이터 수집하기

In [6]:
# 전체 페이지수 구하기
if response['body']['totalCount'] % 1000 == 0:
    total_pages = response['body']['totalCount'] // 1000 
else:
    total_pages = response['body']['totalCount'] // 1000 + 1
total_pages

39

In [1]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [8]:
result={}
page = 1
total_pages = 1
while True:
    # 종료{} 조건 주기
    if page > total_pages:
        break
    
    url="https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    payload = dict(divId="indsSclsCd",key="I21006", numOfRows=1000, pageNo=page, type="json", serviceKey=os.getenv("service_key"))
    r = requests.get(url,params=payload)
    print(r.url)
    # print(r.status_code)
    response = r.json()

    # 전체 페이지수 구하기
    if total_pages == 1:
        if response['body']['totalCount'] % 1000 == 0:
            total_pages = response['body']['totalCount'] // 1000 
        else:
            total_pages = response['body']['totalCount'] // 1000 + 1
    

        
    # 현재 수집 페이지 출력
    print(f"{page}/{total_pages} 수집중     ", end="\r")
    
    # 가게 정보 추출
    for item in response['body']['items']:
        for key, value in item.items():
            result.setdefault(key,[]).append(value)
        
    page += 1
    time.sleep(0.5)
    
df = pd.DataFrame(result)
df

https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=1&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=2&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=3&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=4&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=5&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=6&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=7&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=8&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=9&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=10&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=11&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=12&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=13&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=14&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=15&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=16&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=17&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=18&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=19&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=20&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=21&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=22&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=23&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=24&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=25&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=26&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=27&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=28&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=29&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=30&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=31&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=32&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=33&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=34&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=35&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=36&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D

https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=37&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=38&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D
https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=39&type=json&serviceKey=Lsn7fOQsOf0UbSazp02tQqhHvCRCUoArvYqhvhBAZYLzcD1h3B6k1OcnF532ru6zETlPVfUU6fNaP8FQ6AZcyA%3D%3D

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800497493,라피노치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1150010800100340040006076,,서울특별시 강서구 공항대로8길 11,157812,07624,,1,,126.812380,37.560568
1,MA010120220800507495,썬더치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1150010300103530093014082,,서울특별시 강서구 강서로17다길 6,157882,07769,,,,126.842341,37.532789
2,MA010120220800416449,통다리치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,2818510200103560001043236,,인천광역시 연수구 선학로68번길 7-5,406090,21910,,1,,126.701486,37.423982
3,MA010120220800645292,누나홀닭평내,호평점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4136010100101650004015245,,경기도 남양주시 호평로67번길 1,472120,12147,,,,127.247323,37.656314
4,MA010120220800103915,금강두마리치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4423025032102490002051821,금강빌리지임대,충청남도 논산시 강경읍 동안로 96,320904,32942,,,,127.022380,36.151406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38395,MA0106202507A1225972,노랑통닭 미사역점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4145010900108300061000001,,경기도 하남시 미사강변중앙로 157,465150,12913,,,,127.190744,37.560608
38396,MA0106202507A2084239,가마치통닭 용인동백점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4146311600108380000000766,,경기도 용인시 기흥구 동백5로 22,446766,17006,,,,127.151281,37.275962
38397,MA0106202507A0834201,솜리치킨에코시티점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4511312200113270015000001,,전북특별자치도 전주시 덕진구 세병2길 19,561302,55149,,,,127.126157,35.872916
38398,MA0106202507A0594715,낭만장작창원팔용점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4812112900101740007018198,,경상남도 창원시 의창구 남산로27번길 7,641851,51368,,,,128.613482,35.259426
38399,MA0106202508A1589715,또봉이통닭이천고담행복5문점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,4150035028100010005000236,,경기도 이천시 대월면 대산로288번길 72,467852,17336,,,,127.475370,37.249398

In [7]:
response['body']['totalCount']

38400

# 업종 데이터를 불러와서 업종별 가게 리스트 csv 파일 만들기
* shops_data 폴더에 저장
* 소분류명_가게리스트.csv

In [3]:
# 업종파일 xlsx 파일 불러와서 업종 리스트 추출하기
# !pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [8]:
upjong_list = pd.read_excel("./상권상가API_메뉴얼/소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.xlsx", header=1)
upjong_codes = upjong_list['소분류코드']
upjong_name  = upjong_list['소분류명']

In [6]:
for code in upjong_codes:
    print(code)

G20201
G20202
G20301
G20404
G20405
G20499
G20501
G20502
G20503
G20504
G20505
G20506
G20507
G20508
G20509
G20601
G20602
G20603
G20604
G20701
G20801
G20802
G20803
G20901
G20902
G20903
G20904
G20905
G20906
G20907
G20908
G20909
G20910
G20911
G21001
G21002
G21003
G21099
G21101
G21201
G21202
G21203
G21301
G21302
G21303
G21304
G21305
G21306
G21401
G21402
G21403
G21501
G21502
G21503
G21601
G21602
G21603
G21701
G21801
G21802
G21901
G22001
G22199
G22201
I10101
I10102
I10103
I10104
I10201
I10299
I20101
I20102
I20103
I20104
I20105
I20106
I20107
I20108
I20109
I20110
I20111
I20112
I20113
I20199
I20201
I20202
I20301
I20302
I20303
I20399
I20401
I20402
I20403
I20499
I20501
I20599
I20601
I20701
I20702
I21001
I21002
I21003
I21004
I21005
I21006
I21007
I21008
I21099
I21101
I21102
I21103
I21104
I21201
L10203
M10301
M10302
M10303
M10306
M10307
M10399
M10401
M10402
M10499
M10501
M10502
M10503
M10504
M10599
M10601
M10703
M10901
M10902
M10903
M10904
M10999
M11101
M11201
M11202
M11203
M11204
M11301
M11401
M11502
M11504
N10101
N10201
N10202
N10203
N10301
N10401
N10402
N10403
N10501
N10599
N10703
N10799
N10802
N10805
N10901
N10999
N11001
N11002
N11003
N11004
N11099
N11101
N11102
N11199
P10501
P10601
P10603
P10605
P10607
P10609
P10611
P10613
P10615
P10617
P10619
P10621
P10623
P10625
P10627
P10629
P10701
P10799
Q10101
Q10102
Q10103
Q10104
Q10105
Q10201
Q10202
Q10203
Q10204
Q10205
Q10206
Q10207
Q10208
Q10209
Q10210
Q10211
Q10212
Q10402
R10202
R10306
R10307
R10308
R10309
R10310
R10311
R10312
R10313
R10314
R10316
R10402
R10404
R10405
R10406
R10407
R10408
R10409
R10410
R10414
R10499
S20101
S20201
S20301
S20302
S20401
S20501
S20601
S20602
S20603
S20699
S20701
S20702
S20703
S20801
S20802
S20803
S20901
S20902
S21001
S21002
S21101
S21105

In [12]:
for name in upjong_name:
    print(name)

타이어 소매업
자동차 부품 소매업
모터사이클 및 부품 소매업
슈퍼마켓
편의점
그 외 기타 종합 소매업
곡물/곡분 소매업
가축 사료 소매업
정육점
건어물/젓갈 소매업
수산물 소매업
채소/과일 소매업
아이스크림 할인점
건강보조식품 소매업
반찬/식료품 소매업
얼음 소매업
주류 소매업
생수/음료 소매업
우유 소매업
담배/전자담배 소매업
컴퓨터/소프트웨어 소매업
핸드폰 소매업
가전제품 소매업
남성 의류 소매업
여성 의류 소매업
유아용 의류 소매업
한복 소매업
기타 의류 소매업
침구류/커튼 소매업
액세서리/잡화 소매업
가발 소매업
실/섬유제품 소매업
신발 소매업
가방 소매업
철물/공구 소매업
벽지/장판/마루 소매업
건설/건축자재 소매업
기타 건설/건축자재 소매업
가구 소매업
전기용품/조명장치 소매업
주방/가정용품 소매업
악기 소매업
서점
문구/회화용품 소매업
음반/비디오물 소매업
운동용품 소매업
자전거 소매업
장난감 소매업
주유소
가스 충전소
가정용 연료 소매업
약국
의료기기 소매업
화장품 소매업
사무기기 소매업
안경렌즈 소매업
사진기/기타 광학기기 소매업
시계/귀금속 소매업
예술품 소매업
기념품점
꽃집
애완동물/애완용품 소매업
그 외 기타 상품 전문 소매업
중고 상품 소매업
호텔/리조트
여관/모텔
펜션
캠핑/글램핑
기숙사/고시원
그 외 기타 숙박업
백반/한정식
국/탕/찌개류
족발/보쌈
전/부침개
국수/칼국수
냉면/밀면
돼지고기 구이/찜
소고기 구이/찜
곱창 전골/구이
닭/오리고기 구이/찜
횟집
해산물 구이/찜
복 요리 전문
기타 한식 음식점
중국집
마라탕/훠궈
일식 회/초밥
일식 카레/돈가스/덮밥
일식 면 요리
기타 일식 음식점
경양식
파스타/스테이크
패밀리레스토랑
기타 서양식 음식점
베트남식 전문
기타 동남아식 전문
분류 안된 외국식 음식점
구내식당
뷔페
빵/도넛
떡/한과
피자
버거
토스트/샌드위치/샐러드
치킨
김밥/만두/분식
아이스크림/빙수
그 외 기타 간이 음식점
일반 유흥 주점
무도 유흥 주점
생맥주 전문
요리 주점
카페
부동산 중개/대리업
변호사
변리사
법무사
행정사
공인노무사
기타 법무관련 서비스업
공인회계사
세무사
기타 회계 관련 서비스업
광고 대행업
옥외/전시 광고 대행업
광고 매체 판매업
광고물 설계/제작업
기타 광고 관련 서비스업
시장 조사 및 여론 조사업
경영 컨설팅업
건축 설계 및 관련 서비스업
도시 계획 및 조경 설계 서비스업
건물 및 토목 엔지니어링 서비스업
환경 관련 엔지니어링 서비스업
기타 엔지니어링 서비스업
동물병원
인테리어 디자인업
제품 디자인업
시각 디자인업
패션/섬유/기타 전문 디자인업
사진촬영업
명함/간판/광고물 제작
번역/통역 서비스업
사업/무형 재산권 중개업
사업시설 유지·관리 서비스업
건축물 일반 청소업
산업설비, 운송장비 및 공공장소 청소업
소독, 구충 및 방제 서비스업
조경 유지·관리 서비스업
고용 알선업
임시/일용 인력 공급업
상용 인력 공급 및 인사관리 서비스업
여행사
기타 여행 보조/예약 서비스업
복사업
기타 사무 지원 서비스업
전시/컨벤션/행사 대행 서비스업
포장/충전업
자동차 대여업
기타 운송장비 대여업
스포츠/레크리에이션 용품 대여업
음반/비디오물 대여업
만화방
의류 대여업
기타 개인/가정용품 대여업
건설기계/장비 대여업
컴퓨터/사무기기 대여업
기타 산업용 기계/장비 대여업
입시·교과학원
태권도/무술학원
요가/필라테스 학원
레크리에이션 교육기관
청소년 수련시설
음악학원
미술학원
기타 예술/스포츠 교육기관
외국어학원
전문자격/고시학원
사회교육시설
직원 훈련기관
운전학원
기타 기술/직업 훈련학원
컴퓨터 학원
그 외 기타 교육기관
교육컨설팅업
기타 교육지원 서비스업
종합병원
일반병원
치과병원
한방병원
요양병원
내과/소아과 의원
외과 의원
신경/정신과 의원
피부/비뇨기과 의원
안과 의원
이비인후과 의원
산부인과 의원
성형외과 의원
기타 의원
치과의원
한의원
방사선 진단/병리 검사 의원
유사 의료업
독서실/스터디 카페
종합 스포츠시설
헬스장
수영장
볼링장
당구장
골프 연습장
테니스장
탁구장
기타 스포츠시설 운영업
스쿼시/라켓볼장
비디오방
전자 게임장
기타 오락장
PC방
노래방
낚시터 운영업
수상/해양 레저업
복권 발행/판매업
바둑/장기/체스 경기 운영업
기타 오락관련 서비스업
컴퓨터/노트북/프린터 수리업
핸드폰/통신장비 수리업
자동차 정비소
자동차 세차장
모터사이클 수리업
가전제품 수리업
의류/이불 수선업
가죽/가방/신발 수선업
시계/귀금속/악기 수리업
그 외 기타 개인/가정용품 수리업
미용실
피부 관리실
네일숍
목욕탕/사우나
마사지/안마
체형/비만 관리
세탁소
셀프 빨래방
장례식장
화장터/묘지/납골당
예식장업
결혼 상담 서비스업

In [20]:
for code, name in zip(upjong_list['소분류코드'][:2],upjong_list['소분류명']):
    print(code, name)

G20201 타이어 소매업
G20202 자동차 부품 소매업

In [1]:
import os
import time
import requests
import pandas as pd
from dotenv import load_dotenv
load_dotenv()

True

In [9]:
for idx, (code, name) in enumerate(zip(upjong_list['소분류코드'], upjong_list['소분류명'])):
    result ={}
    page = 1
    total_pages = 1
    while True:

        # 종료 조건 주기
        if page > total_pages:
            break

        url = "https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
        payload = dict(divId="indsSclsCd", key=code, numOfRows=1000, pageNo=page, type="json", serviceKey=os.getenv("service_key"))
        r = requests.get(url, params=payload)
    #     print(r.url)
    #     print(r.status_code)
        response = r.json()

        # 전체 페이지수 구하기
        if total_pages == 1:
            if response['body']['totalCount'] % 1000 == 0:
                total_pages = response['body']['totalCount'] // 1000 
            else:
                total_pages = response['body']['totalCount'] // 1000 +1

        # 현재 수집 페이지 출력
        print(f"{idx}/{len(upjong_list['소분류코드'])}_{name}_{page}/{total_pages} 수집중    ", end="\r")

        # 가게 정보 추출
        for item in response['body']['items']:
            for key, value in item.items():
                result.setdefault(key, []).append(value)

        page += 1
        time.sleep(0.5)

    df = pd.DataFrame(result)
    
    dir_name = "shops_data"
    if not os.path.exists(dir_name):
        os.mkdir(dir_name)
        print(f"{dir_name}을 생성했습니다.")
    else:
        print(f"{dir_name}이 이미 있습니다.")
    
    df.to_csv(f"./shops_data/{name}_가게리스트.csv")

shops_data을 생성했습니다.집중

KeyboardInterrupt: